apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: psv1
    port: 30022
    protocol: TCP
    targetPort: 30022
  - name: psv2
    port: 30023
    protocol: TCP
    targetPort: 30023
  - name: psv3
    port: 30024
    protocol: TCP
    targetPort: 30024
  - name: psv4
    port: 30025
    protocol: TCP
    targetPort: 30025
  - name: psv5
    port: 30026
    protocol: TCP
    targetPort: 30026
  - name: psv6
    port: 30027
    protocol: TCP
    targetPort: 30027

  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: service_ftps
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30022
        - containerPort: 30023
        - containerPort: 30024
        - containerPort: 30025
        - containerPort: 30026
        - containerPort: 30027
      restartPolicy: Always
